(function(root){
'use strict';
const HISTORY='donRamonBackupHistoryV1',LIMIT=10;
const keyOK=k=>/^donRamon[A-Za-z0-9_-]+$/.test(k)&&k!==HISTORY&&k!=='donRamonCleanStartV1';
function snapshot(storage){const data={};for(let i=0;i<storage.length;i++){const k=storage.key(i);if(keyOK(k))data[k]=storage.getItem(k);}return data;}
function validate(copy){if(!copy||copy.format!=='don-ramon-backup'||copy.version!==1||!copy.data||Array.isArray(copy.data)||typeof copy.data!=='object')throw Error('No es una copia JSON compatible de Don Ramón.');const keys=Object.keys(copy.data);if(!keys.includes('donRamonV5'))throw Error('La copia no contiene la ficha principal de la app.');for(const k of keys){if(!keyOK(k)||typeof copy.data[k]!=='string')throw Error('La copia contiene campos no compatibles.');try{JSON.parse(copy.data[k]);}catch{throw Error('Datos dañados en '+k+'.');}}const main=JSON.parse(copy.data.donRamonV5);if(!main||!Array.isArray(main.inquilinas)||main.inquilinas.some(t=>!t||typeof t!=='object'||!t.id||typeof t.nombre!=='string')||!main.cobrosByMonth||typeof main.cobrosByMonth!=='object'||Array.isArray(main.cobrosByMonth)||Object.values(main.cobrosByMonth).some(v=>!Array.isArray(v)))throw Error('Las fichas o los cobros de la copia tienen un formato incorrecto.');for(const k of ['donRamonGastosReal','donRamonGastosV12'])if(copy.data[k]){const v=JSON.parse(copy.data[k]);if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Los gastos de la copia tienen un formato incorrecto.');if(k==='donRamonGastosReal'&&Object.values(v).some(rows=>!Array.isArray(rows)))throw Error('Los apuntes de gastos no son compatibles.');}return copy;}
function envelope(data){return {format:'don-ramon-backup',version:1,createdAt:new Date().toISOString(),data};}
function restore(storage,copy){validate(copy);const before=snapshot(storage);try{for(const k of Object.keys(before))storage.removeItem(k);for(const [k,v] of Object.entries(copy.data))storage.setItem(k,v);}catch(e){try{for(const k of Object.keys(snapshot(storage)))storage.removeItem(k);for(const [k,v] of Object.entries(before))storage.setItem(k,v);}catch{throw Error('No hay espacio para restaurar y recuperar los datos. Conserva la copia JSON y no cierres la app.');}throw Error('No se pudo restaurar. Los datos anteriores se han conservado.');}}
const api={snapshot,validate,envelope,restore,keyOK};if(typeof module==='object')module.exports=api;if(!root.document)return;
const storage=root.localStorage,originalSet=Storage.prototype.setItem,originalRemove=Storage.prototype.removeItem;let timer,paused=false,last='',notice='',pending=null;
function history(){try{return JSON.parse(storage.getItem(HISTORY)||'[]');}catch{return [];}}
function saveVersion(){clearTimeout(timer);if(paused)return;const data=snapshot(storage);if(!data.donRamonV5)return;const stamp=JSON.stringify(data);if(stamp===last)return;let list=history();if(list[0]&&JSON.stringify(list[0].data)===stamp){last=stamp;return;}list.unshift(envelope(data));list=list.slice(0,LIMIT);try{originalSet.call(storage,HISTORY,JSON.stringify(list));last=stamp;notice='';}catch{notice='No hay espacio para guardar otra versión. Descarga una copia JSON.';}updateStatus();}
function changed(k){if(!paused&&keyOK(String(k))){clearTimeout(timer);timer=setTimeout(saveVersion,600);}}
Storage.prototype.setItem=function(k,v){originalSet.call(this,k,v);if(this===storage)changed(k);};Storage.prototype.removeItem=function(k){originalRemove.call(this,k);if(this===storage)changed(k);};
// Flush changes before navigations that follow document incorporation.
root.addEventListener('pagehide',saveVersion);root.addEventListener('storage',e=>{if(e.storageArea===storage&&e.key&&keyOK(e.key))changed(e.key);});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function summary(copy){const m=JSON.parse(copy.data.donRamonV5);const expenses=JSON.parse(copy.data.donRamonGastosReal||'{}');return m.inquilinas.length+' inquilinas · '+Object.values(m.cobrosByMonth).reduce((n,x)=>n+x.length,0)+' apuntes de cobros · '+Object.values(expenses).reduce((n,x)=>n+x.length,0)+' gastos';}
function updateStatus(){const el=document.getElementById('backup-status');if(el)el.textContent=notice||('Guardado local automático. Última versión: '+(history()[0]?new Date(history()[0].createdAt).toLocaleString('es-ES'):'pendiente'));}
function download(){saveVersion();try{const copy=validate(envelope(snapshot(storage)));const url=URL.createObjectURL(new Blob([JSON.stringify(copy,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Don-Ramon-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);document.getElementById('backup-message').textContent='Copia preparada. Comprueba que se haya guardado en Descargas o Archivos.';}catch(e){message(e.message);}}
function message(text){document.getElementById('backup-message').textContent=text;}
function preview(copy){try{pending=validate(copy);document.getElementById('backup-preview').innerHTML='<strong>Copia del '+esc(new Date(copy.createdAt).toLocaleString('es-ES'))+'</strong><p>'+esc(summary(copy))+'</p><p>Reemplazará todos los datos actuales de esta app. Antes se conservará una versión local de los datos actuales.</p><button id="backup-confirm" type="button">Confirmar restauración</button> <button id="backup-cancel" type="button">Cancelar</button>';document.getElementById('backup-confirm').onclick=()=>{try{saveVersion();if(notice)throw Error('Descarga primero una copia de los datos actuales: no hay espacio para conservar una versión anterior.');paused=true;restore(storage,pending);paused=false;last='';saveVersion();location.reload();}catch(e){paused=false;message(e.message);}};document.getElementById('backup-cancel').onclick=()=>{pending=null;document.getElementById('backup-preview').textContent='';};}catch(e){pending=null;message(e.message);}}
let backupOpener;
root.openBackupModal=function(button){backupOpener=button;open();};
function open(){saveVersion();const panel=document.getElementById('backup-panel');panel.hidden=false;panel.querySelector('#backup-close').focus();updateStatus();const list=document.getElementById('backup-history');list.innerHTML=history().map((c,i)=>'<button type="button" data-version="'+i+'" style="text-align:left;display:block;width:100%;margin:8px 0;">'+esc(new Date(c.createdAt).toLocaleString('es-ES'))+' · Revisar versión</button>').join('')||'Todavía no hay versiones.';list.querySelectorAll('[data-version]').forEach(b=>b.onclick=()=>preview(history()[Number(b.dataset.version)]));}
function init(){const host=document.createElement('div');host.innerHTML='<div id="backup-panel" hidden style="position:fixed;inset:0;z-index:10000;background:#0006;padding:16px;overflow:auto;"><section role="dialog" aria-modal="true" aria-label="Copia de seguridad" style="max-width:600px;margin:24px auto;background:white;border-radius:20px;padding:24px;font-size:16px;color:#0f172a;"><button id="backup-close" type="button" style="float:right;" aria-label="Cerrar">×</button><div class="dr-tool-icon" aria-hidden="true">💾</div><h2 style="font-size:22px;">Copia de seguridad</h2><p id="backup-status"></p><p>Los cambios se guardan en este navegador. Se conservan hasta 10 versiones locales. Si borras los datos del sitio, también se borran esas versiones.</p><button id="backup-download" type="button">💾 Crear copia de seguridad JSON</button><button id="backup-import" type="button">📂 Importar copia de seguridad JSON</button><input id="backup-file" type="file" accept=".json,application/json" aria-label="Seleccionar copia JSON"><p>La copia incluye los datos guardados de la app. Los PDF originales se conservan aparte.</p><div id="backup-message" role="status" style="color:#1d4ed8;overflow-wrap:anywhere;"></div><div id="backup-preview" style="background:#eff6ff;border-radius:12px;padding:12px;margin-top:12px;"></div><details style="margin-top:20px;"><summary style="font-weight:700;cursor:pointer;">Versiones automáticas</summary><div id="backup-history"></div></details></section></div>';document.body.appendChild(host);document.getElementById('backup-close').onclick=()=>{document.getElementById('backup-panel').hidden=true;backupOpener?.focus();};document.getElementById('backup-download').onclick=download;document.getElementById('backup-import').onclick=()=>document.getElementById('backup-file').click();document.getElementById('backup-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20*1024*1024)throw Error('La copia supera el tamaño admitido de 20 MB.');preview(JSON.parse(await f.text()));}catch(err){message(err instanceof SyntaxError?'El archivo no contiene un JSON válido.':err.message);}e.target.value='';};saveVersion();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(typeof window==='object'?window:globalThis);
