(function(root){
'use strict';
const KEY='donRamonDashboardOrderV1';
const IDS=['income','expenses','profit','occupancy','entries','deposits','expirations','notes','assistant'];
function reconcile(saved,ids){return [...new Set((Array.isArray(saved)?saved:[]).filter(id=>ids.includes(id)).concat(ids))];}
function restore(saved){return reconcile((Array.isArray(saved)?saved:[]).map(id=>/^card-\d+$/.test(id)?IDS[Number(id.slice(5))]:id),IDS);}
function move(list,id,target){const out=list.filter(x=>x!==id),index=out.indexOf(target);out.splice(index<0?out.length:index,0,id);return out;}
if(typeof module==='object')module.exports={reconcile,move,canStart,restore,IDS};if(!root.document)return;
let grid,order=[],drag=null,pending=null,blockUntil=0,frame=0;
const cards=()=>grid?[...grid.children].filter(x=>x.dataset.drCard):[];
function apply(){cards().forEach(c=>{const n=order.indexOf(c.dataset.drCard);if(c.style.order!==String(n))c.style.order=n;});}
function setup(){const next=document.getElementById('dashboard-order-grid');if(!next){if(drag)finish(true);return;}if(next!==grid){finish(true);grid=next;let saved=[];try{saved=JSON.parse(localStorage.getItem(KEY)||'[]');}catch{}order=restore(saved);}cardsInit();apply();}
function cardsInit(){let nativeIndex=0;[...grid.children].forEach(c=>{c.dataset.drCard=c.dataset.documentAssistant==='1'?'assistant':IDS[nativeIndex++];c.setAttribute('aria-description','Mantén pulsado para cambiar de posición.');});order=restore(order);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(order));return true;}catch{if(!document.getElementById('dashboard-order-save-error')){const notice=document.createElement('div');notice.id='dashboard-order-save-error';notice.setAttribute('role','alert');notice.textContent='No se pudo guardar el orden. Comprueba el espacio y los permisos de almacenamiento del navegador.';notice.style.cssText='position:fixed;top:16px;left:16px;right:16px;z-index:210000;background:#fff7ed;color:#9a3412;padding:16px;border:1px solid #fed7aa;border-radius:14px;font-size:16px;';document.body.appendChild(notice);setTimeout(()=>notice.remove(),8000);}return false;}}
function cardAt(target){let c=target;while(c&&c.parentElement!==grid)c=c.parentElement;return c?.dataset.drCard?c:null;}
function canStart(c,target){const control=target.closest('button,a,input,select,textarea');return !!c&&(!control||control===c);}
function start(c,x,y){cancel();pending={c,x,y,timer:setTimeout(()=>activate(c,x,y),450)};}
function activate(c,x,y){if(!c.isConnected)return cancel();pending=null;root.getSelection?.()?.removeAllRanges();const rect=c.getBoundingClientRect(),clone=c.cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(el=>el.removeAttribute('id'));clone.setAttribute('aria-hidden','true');clone.style.cssText='position:fixed;pointer-events:none;z-index:200000;width:'+rect.width+'px;left:'+rect.left+'px;top:'+rect.top+'px;margin:0;transform:scale(1.03);box-shadow:0 12px 36px #0f172a40;opacity:.96;';document.body.appendChild(clone);drag={c,clone,x,y,dx:x-rect.left,dy:y-rect.top,before:order.slice(),lastTarget:null};c.style.opacity='.25';document.body.classList.add('dr-order-active');navigator.vibrate?.(20);frame=requestAnimationFrame(scroll);}
function update(x,y){if(!drag){if(pending&&Math.hypot(x-pending.x,y-pending.y)>10)cancel();return;}drag.x=x;drag.y=y;drag.clone.style.left=x-drag.dx+'px';drag.clone.style.top=y-drag.dy+'px';const target=cards().filter(c=>c!==drag.c).map(c=>{const r=c.getBoundingClientRect();return {c,r,d:Math.hypot(x-(r.left+r.width/2),y-(r.top+r.height/2))};}).sort((a,b)=>a.d-b.d)[0];if(target&&target.d<Math.max(target.r.width,target.r.height)*.6&&drag.lastTarget!==target.c.dataset.drCard){const id=drag.c.dataset.drCard,t=target.c.dataset.drCard,to=order.indexOf(t);order=order.filter(k=>k!==id);order.splice(to,0,id);drag.lastTarget=t;apply();persist();}else if(target&&target.d>Math.max(target.r.width,target.r.height)*.7)drag.lastTarget=null;}
function scroll(){if(!drag)return;const y=drag.y,dy=y<80?-9:y>innerHeight-80?9:0;if(dy){let host=grid.parentElement;while(host&&host!==document.body){if(host.scrollHeight>host.clientHeight&&/(auto|scroll)/.test(getComputedStyle(host).overflowY))break;host=host.parentElement;}if(host&&host!==document.body)host.scrollTop+=dy;else root.scrollBy(0,dy);update(drag.x,drag.y);}frame=requestAnimationFrame(scroll);}
function finish(save=true){if(pending){clearTimeout(pending.timer);pending=null;}if(!drag)return;cancelAnimationFrame(frame);drag.c.style.opacity='';drag.clone.remove();if(!save)order=drag.before;persist();drag=null;document.body.classList.remove('dr-order-active');blockUntil=Date.now()+500;apply();}
function cancel(){finish(false);}
function init(){const style=document.createElement('style');style.textContent='#dashboard-order-grid,#dashboard-order-grid *{-webkit-touch-callout:none;-webkit-user-select:none;user-select:none}body.dr-order-active{user-select:none;-webkit-user-select:none}body.dr-order-active #dashboard-order-grid>*{transition:opacity .15s}';document.head.appendChild(style);setup();const observer=new MutationObserver(setup);observer.observe(document.getElementById('root')||document.body,{childList:true,subtree:true});
 document.addEventListener('touchstart',e=>{if(e.touches.length!==1){cancel();return;}const c=cardAt(e.target);if(canStart(c,e.target))start(c,e.touches[0].clientX,e.touches[0].clientY);},{passive:true});
 document.addEventListener('touchmove',e=>{if(e.touches.length!==1)return finish(true);if(drag)e.preventDefault();update(e.touches[0].clientX,e.touches[0].clientY);},{passive:false});document.addEventListener('touchend',()=>finish(),{passive:true});document.addEventListener('touchcancel',()=>finish(true),{passive:true});
 document.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.button!==0)return;const c=cardAt(e.target);if(canStart(c,e.target))start(c,e.clientX,e.clientY);});document.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;update(e.clientX,e.clientY);});document.addEventListener('pointerup',e=>{if(e.pointerType!=='touch')finish();});document.addEventListener('pointercancel',e=>{if(e.pointerType!=='touch')finish(true);});
 document.addEventListener('click',e=>{if(drag||Date.now()<blockUntil){e.preventDefault();e.stopImmediatePropagation();}},true);document.addEventListener('contextmenu',e=>{if(cardAt(e.target))e.preventDefault();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){e.preventDefault();e.stopImmediatePropagation();cancel();}},true);root.addEventListener('blur',()=>finish(true));root.addEventListener('pagehide',()=>finish(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')finish(true);});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(typeof window==='object'?window:globalThis);
