(function(root){
'use strict';
function install(React){
 const h=React.createElement,C=root.DonRamonDepositCore,K=root.DonRamonContracts;
 const input='w-full bg-white border border-[#e5e7eb] rounded-[12px] px-4 py-3 text-[14px] outline-none focus:border-[#2b5cff]/40 focus:ring-2 focus:ring-[#eef4ff]';
 const primary='w-full h-[48px] rounded-[14px] bg-[#2b5cff] text-white font-bold text-[15px] shadow-[0_8px_20px_rgba(43,92,255,.25)]';
 const secondary='w-full h-[44px] rounded-[12px] border border-[#e5e7eb] bg-white text-[#2b5cff] font-bold text-[14px]';
 const euros=value=>Number(value||0).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
 const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date());
 const date=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')?value.split('-').reverse().join('/'): 'Sin indicar';
 function Menu({label,value,options,onChange}){
  const [open,setOpen]=React.useState(false),box=React.useRef(null);
  React.useEffect(()=>{if(!open)return;const close=e=>{if(!box.current?.contains(e.target))setOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[open]);
  return h('div',{className:'flex flex-col gap-2',ref:box},h('span',{className:'text-[14px] font-bold text-slate-900'},label),h('div',{className:'relative'},h('button',{type:'button',className:input+' font-bold text-left flex items-center justify-between','aria-expanded':open,'aria-label':label,onClick:()=>setOpen(!open),onKeyDown:e=>{if(e.key==='Escape')setOpen(false);}},h('span',null,options.find(o=>o.value===value)?.label||value||'Sin indicar'),h('span',{className:'text-slate-400 text-[12px] flex flex-col leading-none','aria-hidden':true},h('span',{className:'text-[9px] -mb-0.5'},'⌃'),h('span',{className:'text-[9px]'},'⌄'))),open&&h('div',{className:'absolute z-30 left-0 right-0 mt-2 bg-white border border-[#e5e7eb] rounded-[12px] shadow-[0_8px_24px_rgba(0,0,0,.08)] overflow-hidden'},options.map(o=>h('button',{key:o.value,type:'button',className:'w-full text-left px-4 py-3 text-[14px] hover:bg-[#f8fafc] '+(value===o.value?'bg-[#eef4ff] font-bold text-[#2b5cff]':'text-slate-900'),onClick:()=>{onChange(o.value);setOpen(false);}},o.label)))));
 }
 const methods=['Transferencia','Bizum','Efectivo'].map(value=>({value,label:value}));
 const field=(label,type,value,onChange,extra={})=>h('label',{className:'flex flex-col gap-2'},h('span',{className:'text-[14px] font-bold text-slate-900'},label),h('input',{type,value,onChange:e=>onChange(e.target.value),className:input,...extra}));
 function Overlay({title,onClose,children}){return h('div',{className:'fixed inset-0 flex items-center justify-center p-4',style:{zIndex:1300,background:'rgba(0,0,0,.5)',backdropFilter:'blur(6px)'},onClick:e=>{if(e.target===e.currentTarget)onClose();}},h('div',{role:'dialog','aria-modal':true,'aria-label':title,className:'bg-white w-full max-w-[650px] max-h-[85vh] overflow-y-auto shadow-[0_24px_64px_rgba(0,0,0,.25)]',style:{borderRadius:24,padding:24}},h('div',{className:'flex items-start justify-between gap-3 mb-4'},h('div',{className:'font-extrabold text-[18px] text-slate-900'},title),h('button',{type:'button',onClick:onClose,'aria-label':'Cerrar',className:'w-9 h-9 rounded-full bg-[#f5f7fb] text-slate-500 font-bold shrink-0'},'✕')),children));}
 function Operation({data,record,mode,movement,onChange,onClose}){
  const [values,setValues]=React.useState(()=>({tipo:'completa',importe:record.importeRecibido,fecha:mode==='ingreso'?record.fechaIngreso||'':mode==='historial'?movement?.fecha||'':today(),metodo:record.medioIngreso||'Sin indicar',recibida:record.recibida,medio:movement?.medio||'Transferencia',devuelto:'',aplicado:C.balance(record),destino:'pendiente',motivo:movement?.motivo||'',notas:movement?.notas||'',periodoDeuda:''})),[error,setError]=React.useState('');
  const set=(key,value)=>setValues(old=>({...old,[key]:value}));const saldo=C.balance(record);
  const returned=values.tipo==='completa'?saldo:values.tipo==='parcial'?Number(values.devuelto||0):0;
  const applied=values.tipo==='compensacion'?Number(values.aplicado||0):values.tipo==='parcial'&&values.destino==='ingreso'?Math.max(0,saldo-returned):0;
  const submit=e=>{e.preventDefault();try{let next;if(mode==='ingreso')next=C.saveReceipt(data,record.id,values);else if(mode==='historial')next=C.editMovement(data,record.id,movement.id,{...values});else next=C.settle(data,record.id,{...values,id:root.crypto?.randomUUID?.()||'op_'+Date.now()+'_'+Math.random(),tipo:values.tipo==='compensacion'?'compensacion':'devolucion',devuelto:returned,aplicado:applied,motivo:values.tipo==='compensacion'?(values.motivo||'Impago de alquiler'):values.motivo});onChange(next);onClose();}catch(err){setError(err.message);}};
  const receipt=mode==='ingreso',history=mode==='historial';
  return h(Overlay,{title:receipt?'✏️ Editar ingreso de fianza':history?'✏️ Completar operación':'⚙️ Gestión de fianza',onClose},h('form',{className:'flex flex-col gap-4',onSubmit:submit},h('div',{className:'text-[14px] font-bold text-slate-900'},record.nombre+' · Habitación '+record.habitacion),
   receipt?h(React.Fragment,null,field('Importe recibido €','number',values.importe,v=>set('importe',v),{min:0,step:'0.01',required:true}),h('label',{className:'flex items-center gap-3 text-[14px] font-bold text-slate-900'},h('input',{type:'checkbox',checked:!!values.recibida,onChange:e=>set('recibida',e.target.checked)}),'Fianza recibida'),field('Fecha de ingreso','date',values.fecha,v=>set('fecha',v)),h(Menu,{label:'Medio de ingreso',value:values.metodo,options:methods,onChange:v=>set('metodo',v)})):
   h(React.Fragment,null,!history&&h(React.Fragment,null,h('div',{className:'font-bold text-[16px] text-slate-900'},'Saldo pendiente: '+euros(saldo)),h(Menu,{label:'Operación',value:values.tipo,options:[{value:'completa',label:'Devolver toda la fianza'},{value:'parcial',label:'Devolución parcial / aplicación por desperfectos'},{value:'compensacion',label:'Compensar alquiler por impago'}],onChange:v=>set('tipo',v)}),values.tipo==='parcial'&&h(React.Fragment,null,field('Importe que devuelves €','number',values.devuelto,v=>set('devuelto',v),{min:0,max:saldo,step:'0.01',required:true}),h(Menu,{label:'Destino del importe restante',value:values.destino,options:[{value:'pendiente',label:'Sigue pendiente de devolver'},{value:'ingreso',label:'Me lo quedo como ingreso por desperfectos u otro motivo'}],onChange:v=>set('destino',v)})),values.tipo==='compensacion'&&h(React.Fragment,null,field('Importe a compensar €','number',values.aplicado,v=>set('aplicado',v),{min:0,max:saldo,step:'0.01',required:true}),field('Mes del alquiler pendiente (imputación)','month',values.periodoDeuda,v=>set('periodoDeuda',v),{required:true})),values.tipo==='compensacion'&&h('div',{className:'text-[14px] text-slate-500'},'El ingreso se contabiliza en el mes del alquiler pendiente, aunque registres la operación más tarde.'),h('div',{className:'bg-[#f8fafc] border border-[#e5e7eb] rounded-[12px] p-3 text-[14px] text-slate-700'},'Devuelto: '+euros(returned)+' · Aplicado como ingreso: '+euros(applied)+' · Pendiente de devolver: '+euros(Math.max(0,saldo-returned-applied)))),
   history&&h('div',{className:'text-[14px] text-slate-700'},'Devuelto: '+euros(movement.devuelto)+' · Aplicado: '+euros(movement.aplicado)),field('Fecha de la operación','date',values.fecha,v=>set('fecha',v),{required:true}),((!history&&returned>0)||(history&&movement.devuelto>0))&&h(Menu,{label:'Medio de devolución',value:values.medio,options:methods,onChange:v=>set('medio',v)}),field('Motivo','text',values.motivo,v=>set('motivo',v),{required:!history&&applied>0}),field('Notas','text',values.notas,v=>set('notas',v))),
   error&&h('div',{role:'alert',className:'text-[14px] text-red-700 bg-red-50 border border-red-200 rounded-[12px] p-3'},error),h('button',{type:'submit',className:primary},receipt?'Guardar ingreso':'Guardar operación'),h('button',{type:'button',className:secondary,onClick:onClose},'Cancelar')));
 }
 function Panel({data,onChange,onClose,tenantId,room,onTenant,onRoom,dashboard=false}){
  const [open,setOpen]=React.useState({}),[historyOpen,setHistoryOpen]=React.useState(false),[operation,setOperation]=React.useState(null);
  const all=(data.fianzasV2?.records||[]).filter(r=>(!tenantId||r.inquilinaId===tenantId)&&(room===undefined||Number(r.habitacion)===Number(room))).map(r=>({...r,nombre:data.inquilinas.find(t=>t.id===r.inquilinaId)?.nombre||r.nombre}));
  const retained=all.filter(r=>C.balance(r)>0),pending=all.filter(r=>!r.recibida),closed=all.filter(r=>r.recibida&&C.balance(r)===0),rows=[...retained,...pending];
  const total=retained.reduce((sum,r)=>sum+C.balance(r),0);
  const historyRows=[...closed].sort((a,b)=>{const latest=r=>r.movimientos.reduce((last,m)=>(m.fecha||'')>last?m.fecha:last,'');return latest(b).localeCompare(latest(a));});
  const movement=(r,m)=>h('div',{key:m.id,className:'bg-white border border-[#e5e7eb] rounded-[12px] p-3 flex flex-col gap-2 text-[14px] text-slate-700'},h('div',null,'Devuelto: '+euros(m.devuelto)+' · Aplicado: '+euros(m.aplicado)),h('div',null,'Fecha: '+date(m.fecha)+' · '+(m.medio||'Sin indicar')),m.tipo==='compensacion'&&m.periodoDeuda&&h('div',{className:'font-bold text-[#2b5cff]'},'Mes de imputación: '+m.periodoDeuda.split('-').reverse().join('/')),h('div',null,m.motivo||'Sin motivo indicado'),m.notas&&h('div',null,'Notas: '+m.notas),h('button',{type:'button',className:secondary+' h-auto min-h-[44px] py-2 px-3',onClick:()=>setOperation({r,movement:m,mode:'historial'})},'✏️ Editar fecha y datos de la operación'));
  const card=r=>{const returned=r.movimientos.reduce((sum,m)=>sum+m.devuelto,0),applied=r.movimientos.reduce((sum,m)=>sum+m.aplicado,0);const tenant=data.inquilinas.find(t=>t.id===r.inquilinaId),agreement=K.list(tenant).find(c=>c.id===r.contratoId),expired=agreement&&K.status(agreement,today())==='historico',saldo=C.balance(r);
   return h('div',{key:r.id,className:'border rounded-[16px] p-4 flex flex-col gap-3',style:{background:expired&&saldo>0?'#fefce8':'#f0fdf4',borderColor:expired&&saldo>0?'#fde68a':'#bbf7d0'}},h('button',{type:'button',className:'w-full text-left flex items-start justify-between gap-3','aria-expanded':!!open[r.id],onClick:()=>setOpen(old=>({...old,[r.id]:!old[r.id]}))},h('div',{className:'min-w-0'},h('div',{className:'font-bold text-[15px] text-slate-900'},'Habitación '+r.habitacion+' · DON RAMÓN'),h('div',{className:'font-bold text-[15px] text-slate-700 mt-1'},r.nombre),h('div',{className:'text-[13px] text-slate-500 mt-1'},!r.recibida?'Ingreso pendiente de confirmar':saldo>0?(expired?'Contrato terminado · fianza pendiente de devolver':'Fianza retenida'):'Fianza gestionada'),r.movimientos.length>0&&h('div',{className:'text-[14px] text-slate-700 mt-1'},'Devuelto: '+euros(returned)+' · Aplicado: '+euros(applied))),h('div',{className:'flex flex-col items-end gap-2 shrink-0'},h('span',{className:'font-extrabold text-[20px] text-slate-900'},euros(saldo)),h('span',{className:'text-slate-500 text-[14px]'},open[r.id]?'▲':'▼'))),open[r.id]&&h('div',{className:'flex flex-col gap-3'},h('div',{className:'bg-white border border-[#f1f5f9] rounded-[12px] p-3 text-[14px] text-slate-700 flex flex-col gap-1.5'},h('div',null,'Importe recibido: '+(r.recibida?euros(r.importeRecibido):'Sin confirmar')),h('div',null,'Fecha de ingreso: '+date(r.fechaIngreso)),h('div',null,'Medio de ingreso: '+(r.medioIngreso||'Sin indicar')),h('div',null,'Contrato: '+date(agreement?.entryDate)+' · '+date(agreement?.exitDate)),h('div',null,'Devuelto: '+euros(r.movimientos.reduce((sum,m)=>sum+m.devuelto,0))),h('div',null,'Aplicado como ingreso: '+euros(r.movimientos.reduce((sum,m)=>sum+m.aplicado,0))),h('div',{className:'font-bold'},'Pendiente de devolver: '+euros(saldo))),r.movimientos.length>0&&h('div',{className:'flex flex-col gap-2'},h('div',{className:'font-bold text-[14px] text-slate-900'},'Operaciones de esta fianza'),[...r.movimientos].sort((a,b)=>(b.fecha||'').localeCompare(a.fecha||'')).map(m=>movement(r,m))),h('button',{type:'button',className:secondary,onClick:()=>setOperation({r,mode:'ingreso'})},'✏️ Editar ingreso de fianza'),saldo>0&&h('button',{type:'button',className:primary,onClick:()=>setOperation({r,mode:'gestion'})},'⚙️ Gestionar devolución / compensación'),onTenant&&h('button',{type:'button',className:secondary,onClick:()=>onTenant(tenant)},'Abrir ficha inquilina'),onRoom&&h('button',{type:'button',className:secondary,onClick:()=>onRoom(r.habitacion)},'Abrir ficha habitación')));
  };
  const content=h('div',{className:'flex flex-col gap-3'},h('div',{className:'text-[14px] text-slate-500'},retained.length+' retenidas · '+euros(total)+' pendientes de devolver'),rows.map(card),!rows.length&&h('div',{className:'text-[14px] text-slate-500 bg-[#f8fafc] rounded-[12px] p-4'},'Sin fianzas pendientes de devolver.'),h('button',{type:'button',className:secondary,'aria-expanded':historyOpen,onClick:()=>setHistoryOpen(!historyOpen)},'📜 Histórico de devoluciones y aplicaciones '+(historyOpen?'▲':'▼')),historyOpen&&h('div',{className:'flex flex-col gap-3'},historyRows.map(card),!historyRows.length&&h('div',{className:'text-[14px] text-slate-500'},'Sin fianzas completamente gestionadas.')),onClose&&h('button',{type:'button',className:secondary,onClick:onClose},'Cerrar'),operation&&h(Operation,{key:operation.r.id+'_'+operation.mode+'_'+(operation.movement?.id||''),data,record:all.find(r=>r.id===operation.r.id)||operation.r,mode:operation.mode,movement:operation.movement,onChange,onClose:()=>setOperation(null)}));
  return dashboard?h(Overlay,{title:'🔒 Fianzas · saldo actual',onClose},content):content;
 }
 root.DonRamonDepositPanel=Panel;root.DonRamonDepositDashboard=props=>h(Panel,{...props,dashboard:true});
}
root.DonRamonDeposits={install};
})(window);
