(function(){
'use strict';
const core=window.DonRamonDocumentCore;
const content=()=>document.getElementById('ia-doc-content');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let job=0,draft=null,previewURL=null,mode='nueva',renewalTarget=null;
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date());
const labels={nombre:'Nombre completo',tipoDocumento:'Tipo de documento',numeroDocumento:'DNI / NIE / pasaporte',email:'Email',telefono:'Teléfono',nacionalidad:'Nacionalidad',ocupacion:'Estudios / ocupación',centroEstudiosTrabajo:'Universidad / centro de estudios o trabajo',domicilioFamiliar:'Domicilio familiar',habitacion:'Habitación',rentaAcordada:'Renta mensual (€)',fianzaImporte:'Fianza acordada (€)',entryDate:'Inicio del contrato',exitDate:'Fin del contrato',concepto:'Concepto',importe:'Importe total (€)',fecha:'Fecha de factura o abono',categoria:'Categoría',referencia:'Referencia o nº de factura',proveedor:'Proveedor / emisor',periodo:'Mes de renta',metodo:'Método de cobro'};
const css='width:100%;box-sizing:border-box;border:1px solid #e5e7eb;border-radius:10px;padding:10px;margin-top:4px;background:white;font-size:14px;color:#0f172a;';
function read(key,fallback){const value=localStorage.getItem(key);if(value===null)return JSON.parse(JSON.stringify(fallback));try{return JSON.parse(value);}catch{throw Error('Los datos guardados no se pueden leer. Exporta una copia desde Ajustes antes de continuar.');}}
function state(){return read('donRamonV5',{inquilinas:window.DonRamonSeeds?.inquilinas||[],cobrosByMonth:window.DonRamonSeeds?.cobrosByMonth||{},compensaciones:{}});}
function tenantOptions(selected,optional=false){return '<option value="">'+(optional?'General · sin inquilina':'Selecciona inquilina')+'</option>'+state().inquilinas.map(t=>'<option value="'+esc(t.id)+'" '+(String(t.id)===String(selected)?'selected':'')+'>'+esc(t.nombre)+(t.habitacion?' · Hab '+esc(t.habitacion):' · Sin habitación')+'</option>').join('');}
window.iaCancel=function(){job++;draft=null;if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null;}document.getElementById('ia-doc-overlay').style.display='none';};
window.openIADoc=function(){renderIAOptions();document.getElementById('ia-doc-overlay').style.display='flex';};
function renderIAOptions(){renewalTarget=null;job++;draft=null;if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null;}
 content().innerHTML=[['nueva','👤','Alta nueva','Crear nueva inquilina','Preparar una ficha desde un contrato.','Inquilina · contrato · renta · fianza','#eff6ff','#bfdbfe'],['completar','📝','Ficha existente','Completar inquilina existente','Rellenar los datos que faltan de la inquilina, habitación y contrato.','Datos personales · habitación · renta · fechas','#f5f3ff','#ddd6fe'],['renovar','🔄','Nuevo contrato','Renovar inquilina existente','Añadir una estancia conservando el contrato anterior.','Misma ficha · misma ID · otra habitación si corresponde','#eff6ff','#bfdbfe'],['gasto','🧾','Gastos y cobros','Crear gasto desde recibo','Revisar una factura o un justificante de alquiler.','Concepto · importe · fecha · categoría','#f0fdf4','#bbf7d0']].map(([action,icon,tag,title,desc,small,bg,border])=>'<button type="button" data-doc-action="'+action+'" style="text-align:left;background:'+bg+';border:1px solid '+border+';border-radius:16px;padding:16px;cursor:pointer;display:flex;flex-direction:column;gap:8px;"><div style="display:flex;width:100%;justify-content:space-between;align-items:center;"><span style="width:40px;height:40px;border-radius:12px;background:white;display:flex;align-items:center;justify-content:center;font-size:20px;">'+icon+'</span><span style="font-size:12px;font-weight:700;">'+tag+'</span></div><div style="font-weight:800;font-size:16px;color:#0f172a;">'+title+'</div><div style="font-size:14px;color:#6b7280;">'+desc+'</div><div style="font-size:12px;color:#2b5cff;font-weight:700;">'+small+'</div><div style="font-size:14px;font-weight:700;">Preparar revisión</div></button>').join('')+'<div style="font-size:13px;color:#6b7280;line-height:1.5;">Lectura local de PDF y fotos. La IA conectada aún no está activada. Los campos no identificados quedan vacíos para que los revises.</div>';
 content().querySelectorAll('[data-doc-action]').forEach(b=>b.onclick=()=>b.dataset.docAction==='renovar'?window.openRenewalDoc():window.iaStart(b.dataset.docAction));
}
window.renderIAOptions=renderIAOptions;
window.iaStart=function(action){mode=action;window._iaModeActual=action;const input=document.getElementById('ia-file-input');input.value='';input.onchange=onFile;input.click();};
function contractHistory(tenant){const rows=window.DonRamonContracts.list(tenant);return '<details style="background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:14px;margin:12px 0;font-size:14px;" open><summary style="font-weight:700;">📄 Contratos registrados ('+rows.length+')</summary>'+rows.map(c=>'<div style="padding:12px 0;border-top:1px solid #e5e7eb;margin-top:8px;"><strong>Habitación '+esc(c.habitacion)+'</strong><br>'+esc(c.entryDate)+' → '+esc(c.exitDate)+'<br>'+Number(c.rentaAcordada||0).toFixed(2)+' €/mes · Fianza acordada: '+Number(c.fianzaImporte||0).toFixed(2)+' € · '+esc(window.DonRamonContracts.status(c,today())==='historico'?'Histórico':window.DonRamonContracts.status(c,today())==='proxima'?'Próxima entrada':'Vigente')+'</div>').join('')+'</details>';}
window.openRenewalDoc=function(target){job++;draft=null;renewalTarget=target||null;document.getElementById('ia-doc-overlay').style.display='flex';
 function show(){const tenant=state().inquilinas.find(t=>String(t.id)===String(renewalTarget));content().innerHTML='<div style="font-size:24px;">🔄</div><h2 style="font-size:24px;font-weight:800;">Renovar con nuevo contrato</h2><label style="font-size:14px;font-weight:700;">Inquilina<select id="renewal-person" style="'+css+'">'+tenantOptions(renewalTarget)+'</select></label>'+(tenant?contractHistory(tenant)+(tenant.fianzaRenovacion?'<p style="background:#eff6ff;border:1px solid #bfdbfe;padding:14px;border-radius:14px;">Fianza de renovación: '+Number(tenant.fianzaRenovacion.acordada).toFixed(2)+' € acordados. '+Number(tenant.fianzaRenovacion.retenida).toFixed(2)+' € retenidos al renovar. Diferencia por revisar: '+Number(tenant.fianzaRenovacion.diferencia).toFixed(2)+' €. Registra los cobros o devoluciones reales desde Fianzas.</p>':''):'<p>Selecciona la ficha de la inquilina que continúa.</p>')+'<p style="font-size:14px;color:#64748b;">Lee el contrato nuevo y revisa habitación, fechas, renta y fianza. Se conservarán los contratos anteriores y la misma ID.</p><button id="renewal-upload" type="button" '+(!tenant?'disabled':'')+' style="'+css+'background:#2b5cff;color:white;border:0;border-radius:14px;font-weight:700;min-height:48px;">📄 Añadir nuevo contrato</button>';document.getElementById('renewal-person').onchange=e=>{renewalTarget=e.target.value;show();};document.getElementById('renewal-upload').onclick=()=>window.iaStart('renovar');}show();};
function progress(message){content().innerHTML='<div role="status" style="padding:24px;text-align:center;"><div style="font-size:24px;">🤖</div><div style="font-weight:800;margin-top:8px;">'+esc(message)+'</div><div style="font-size:13px;color:#6b7280;margin-top:8px;">Leyendo el contenido del documento. Puedes cerrar para cancelar.</div></div>';}
function fail(message){content().innerHTML='<div role="alert" style="background:#fff7ed;border:1px solid #fed7aa;border-radius:12px;padding:16px;color:#9a3412;">'+esc(message)+'</div><button id="doc-back" style="'+css+'font-weight:700;cursor:pointer;">Volver a las opciones</button>';document.getElementById('doc-back').onclick=renderIAOptions;}
async function ocr(image,token){if(!window.Tesseract)throw Error('No se ha podido cargar el lector de fotos. Comprueba la conexión e inténtalo otra vez.');const reader=await window.Tesseract.createWorker('spa+eng',1);try{await reader.setParameters({tessedit_pageseg_mode:'3'});if(token!==job)throw Error('cancelado');const result=await reader.recognize(image);return {text:result.data.text||'',method:'OCR',confidence:result.data.confidence??0};}finally{await reader.terminate();}}
function prepareScan(canvas){
 const context=canvas.getContext('2d');const image=context.getImageData(0,0,canvas.width,canvas.height);
 // Remove yellow highlighting while preserving dark printed text.
 for(let n=0;n<image.data.length;n+=4){const gray=.299*image.data[n]+.587*image.data[n+1]+.114*image.data[n+2];const v=gray>185?255:0;image.data[n]=image.data[n+1]=image.data[n+2]=v;}
 context.putImageData(image,0,0);return canvas;
}
async function readPages(file,token){
 const extension=file.name.split('.').pop().toLowerCase();if(!['pdf','jpg','jpeg','png'].includes(extension))throw Error('Usa un PDF o una imagen JPG o PNG.');if(file.size>25*1024*1024)throw Error('El documento supera 25 MB. Reduce su tamaño sin quitar páginas.');
 if(extension!=='pdf'){progress('Leyendo foto…');return [{page:1,...await ocr(file,token)}];}
 if(!window.pdfjsLib)throw Error('No se ha podido cargar el lector PDF. Comprueba la conexión e inténtalo otra vez.');
 window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
 const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];
 try{if(pdf.numPages>40)throw Error('Este lector admite hasta 40 páginas. Divide el documento y revisa cada parte; no se ha leído parcialmente.');
 for(let n=1;n<=pdf.numPages;n++){if(token!==job)throw Error('cancelado');progress('Leyendo página '+n+' de '+pdf.numPages+'…');const page=await pdf.getPage(n);const items=(await page.getTextContent()).items;const annotations=await page.getAnnotations({intent:'display'});
 let result={...core.pdfPageText(items,annotations),confidence:null};
 if(result.text.replace(/\s/g,'').length<100){progress('Leyendo escaneo · página '+n+' de '+pdf.numPages+'…');const raw=page.getViewport({scale:1}),scale=Math.min(4,3200/Math.max(raw.width,raw.height));const viewport=page.getViewport({scale});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;result=await ocr(prepareScan(canvas),token);canvas.width=canvas.height=0;}
 pages.push({page:n,...result});page.cleanup();
 }
 if(['nueva','completar','renovar'].includes(mode)){
  const fields=core.extract(pages,mode).fields;
  if(['nombre','habitacion','rentaAcordada','fianzaImporte','entryDate','exitDate'].some(key=>!fields[key])){
   for(const result of pages.filter(p=>p.method!=='OCR'&&/(?:REUNIDOS|Y\s+de\s+otra|TERCERO|inicia\s+el\s+d[ií]a)/i.test(p.text))){
    if(token!==job)throw Error('cancelado');progress('Revisando campos superpuestos · página '+result.page+'…');
    const page=await pdf.getPage(result.page);const raw=page.getViewport({scale:1});const viewport=page.getViewport({scale:Math.min(4,3200/Math.max(raw.width,raw.height))});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;try{result.alternative=await ocr(prepareScan(canvas),token);}catch(e){if(token!==job)throw e;result.visualFallbackFailed=true;}finally{canvas.width=canvas.height=0;page.cleanup();}
   }
  }
 }
 return pages;}finally{await pdf.destroy();}
}
async function onFile(event){const file=event.target.files?.[0];if(!file)return;const token=++job;draft=null;progress('Preparando '+file.name+'…');
 try{const bytes=await file.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('');const pages=await readPages(file,token);if(token!==job)return;const result=core.extract(pages,mode);if(!pages.some(p=>p.text.trim()))result.warnings.push('No se ha obtenido texto legible. Puedes introducir los datos comprobándolos en el documento original.');
 if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(file);draft={file,result,hash,mode,stamp:localStorage.getItem('donRamonV5'),selected:mode==='renovar'?(renewalTarget||core.matchTenant(state(),result.fields)):core.matchTenant(state(),result.fields),values:Object.fromEntries(Object.entries(result.fields).map(([k,f])=>[k,f.value]))};renderReview();
 }catch(e){if(token===job)fail(e.message.includes('password')?'El PDF está protegido. Sube una copia que puedas abrir sin contraseña.':e.message);}
}
function field(key,options={}){
 const value=draft.values[key]??'',source=draft.result.fields[key];
 let input;if(key==='habitacion')input='<select id="doc-'+key+'" style="'+css+'"><option value="">Selecciona habitación</option>'+[1,2,3,4,5].map(n=>'<option '+(String(value)===String(n)?'selected':'')+' value="'+n+'">Hab '+n+'</option>').join('')+'</select>';
 else if(key==='tipoDocumento'||key==='categoria'||key==='metodo'){const opts=key==='tipoDocumento'?['Sin indicar','DNI','NIE','Pasaporte','Documento nacional']:key==='categoria'?['',...core.CATEGORIES]:['Sin indicar','Transferencia','Efectivo','Bizum','Tarjeta'];input='<select id="doc-'+key+'" style="'+css+'">'+opts.map(v=>'<option value="'+esc(v)+'" '+(v===value?'selected':'')+'>'+esc(v||'Selecciona categoría')+'</option>').join('')+'</select>';}
 else{const type=['entryDate','exitDate','fecha'].includes(key)?'date':key==='periodo'?'month':['importe','rentaAcordada','fianzaImporte'].includes(key)?'number':key==='email'?'email':'text';input='<input id="doc-'+key+'" type="'+type+'" '+(type==='number'?'step="0.01" min="0" ':'')+'value="'+esc(value)+'" style="'+css+'">';}
 const current=options.tenant?core.existingValue(options.tenant,key):null;const detected=source&&String(source.value)!=='';const filled=!core.missingField(options.tenant,key)&&current!==null&&current!==undefined&&current!=='';const conflict=filled&&detected&&String(current)!==String(source.value);
 return '<div style="padding:10px 0;border-bottom:1px solid #f1f5f9;"><label style="display:block;font-size:14px;font-weight:700;">'+(options.check?'<input type="checkbox" id="use-'+key+'" '+(draft.checked?.includes(key)?'checked':'')+'> ':'')+esc(labels[key])+input+'</label>'+(options.check?'<div style="font-size:13px;color:'+(conflict?'#9a3412':'#6b7280')+';margin-top:6px;">Actual: '+esc(filled?current:'vacío')+(conflict?' · diferente, elige si deseas cambiarlo':'')+'</div>':'')+(source?'<details style="font-size:12px;color:#6b7280;margin-top:6px;"><summary>Origen: página '+esc(source.page)+' · '+esc(source.method)+'</summary><p style="white-space:pre-wrap;overflow-wrap:anywhere;">'+esc(source.quote)+'</p></details>':'<div style="font-size:12px;color:#9a3412;margin-top:6px;">No identificado · completa tras comprobarlo.</div>')+'</div>';
}
function renderReview(){if(!draft)return;const data=state();const isContract=['nueva','completar','renovar'].includes(draft.mode);const tenant=['completar','renovar'].includes(draft.mode)?data.inquilinas.find(t=>String(t.id)===String(draft.selected)):null;
 let html='<div style="display:flex;gap:8px;align-items:center;"><button id="doc-options" style="background:white;border:1px solid #e5e7eb;border-radius:9999px;padding:8px 14px;font-weight:700;font-size:14px;">Volver</button><strong>Propuesta revisable</strong></div><div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:12px;padding:12px;font-size:14px;color:#1e40af;overflow-wrap:anywhere;">'+esc(draft.file.name)+' · '+draft.result.pages.length+' página(s). Lectura local; revisa antes de guardar.</div>';
 if(draft.result.warnings.length)html+='<div role="status" style="background:#fff7ed;border:1px solid #fed7aa;border-radius:12px;padding:12px;font-size:13px;color:#9a3412;">'+draft.result.warnings.map(esc).join('<br>')+'</div>';
 html+='<a href="'+esc(previewURL)+'" target="_blank" rel="noopener noreferrer" style="font-size:14px;color:#2b5cff;font-weight:700;">Ver documento original</a>';
 html+='<form id="doc-form" novalidate style="background:white;border-radius:16px;padding:16px;">';
 if(draft.mode==='renovar'){
  html+='<label style="font-size:14px;font-weight:700;">Inquilina que renueva<select id="doc-target" style="'+css+'">'+tenantOptions(draft.selected)+'</select></label>';
  html+='<p style="font-size:14px;color:#64748b;">Se añade un contrato independiente. Los contratos anteriores, cobros y datos personales se conservan.</p>';
  if(tenant){html+=contractHistory(tenant);const held=tenant.fianza?.estado==='retenida'?Number(tenant.fianza.importe||0):0;const agreed=Number(draft.values.fianzaImporte||0);html+='<div id="renewal-deposit" style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:14px;padding:14px;font-size:14px;">Fianza retenida: '+held.toFixed(2)+' €. Fianza del nuevo contrato: '+agreed.toFixed(2)+' €. Diferencia por revisar: '+(agreed-held).toFixed(2)+' €. No se registra ningún cobro ni devolución.</div>';}
 }
 if(draft.mode==='completar')html+='<label style="font-size:14px;font-weight:700;">Inquilina a completar<select id="doc-target" style="'+css+'">'+tenantOptions(draft.selected)+'</select></label><p style="font-size:13px;color:#6b7280;">Selecciona la ficha existente. Se completan los campos que marques y se actualizan su habitación, contrato y cálculos.</p>';
 if(isContract){
 if(draft.mode==='completar'){
  if(draft.checkedTarget!==draft.selected){draft.checkedTarget=draft.selected;draft.checked=core.completionSelection(tenant,draft.values);}
  html+='<div style="background:#f5f3ff;border:1px solid #ddd6fe;border-radius:12px;padding:12px;margin:12px 0;font-size:13px;"><strong id="doc-selection-count"></strong><p style="margin:6px 0;">Los datos vacíos están seleccionados. Los datos existentes se conservan salvo que marques un cambio.</p><button type="button" id="doc-fill-empty" style="border:1px solid #ddd6fe;border-radius:8px;background:white;padding:8px;font-weight:700;">Seleccionar solo datos que faltan</button></div>';
 }
 html+=(draft.mode==='renovar'?['nombre','numeroDocumento','habitacion','rentaAcordada','fianzaImporte','entryDate','exitDate']:core.CONTRACT_FIELDS).map((key,index)=>(index===0?'<div style="font-weight:800;margin-top:12px;">Datos de la inquilina</div>':key==='habitacion'?'<div style="font-weight:800;margin-top:18px;">Habitación y contrato</div>':'')+field(key,{check:draft.mode==='completar',tenant})).join('');html+='<p style="font-size:13px;color:#6b7280;">La fianza es la cantidad acordada. Leer el contrato no acredita su cobro ni crea ingresos cobrados.</p>';}
 else{html+='<label style="font-size:14px;font-weight:700;">Tipo de recibo<select id="doc-kind" style="'+css+'"><option value="gasto" '+(draft.mode==='gasto'?'selected':'')+'>Gasto / factura</option><option value="cobro" '+(draft.mode==='cobro'?'selected':'')+'>Cobro de alquiler</option></select></label>';
 html+=['concepto','importe','fecha'].map(k=>field(k)).join('');
 if(draft.mode==='gasto'){html+=['categoria','proveedor','referencia'].map(k=>field(k)).join('');html+='<label style="font-size:14px;font-weight:700;display:block;margin-top:12px;">Vincular a inquilina (opcional)<select id="doc-target" style="'+css+'">'+tenantOptions(draft.selected,true)+'</select></label><p style="font-size:13px;color:#6b7280;">Se incorpora a Gastos y al mes de su fecha en Rentabilidad, una sola vez.</p>';}
 else{html+=['periodo','metodo'].map(k=>field(k)).join('');html+='<label style="font-size:14px;font-weight:700;display:block;margin-top:12px;">Inquilina que realiza el pago<select id="doc-target" style="'+css+'">'+tenantOptions(draft.selected)+'</select></label><p style="font-size:13px;color:#6b7280;">Solo confirma un cobro real. Si ya existe uno en ese mes y habitación, deberás revisarlo en Ingresos.</p>';}}
 html+='<details style="margin-top:16px;font-size:13px;"><summary>Ver texto leído ('+draft.result.pages.length+' páginas)</summary><div style="max-height:260px;overflow:auto;">'+draft.result.pages.map(p=>'<strong>Página '+p.page+' · '+esc(p.method)+'</strong><pre style="white-space:pre-wrap;font-family:inherit;overflow-wrap:anywhere;">'+esc(p.text)+'</pre>').join('')+'</div></details><div id="doc-error" role="alert" style="margin:12px 0;color:#b91c1c;font-size:14px;"></div><div style="display:flex;gap:8px;margin-top:12px;"><button type="button" id="doc-discard" style="flex:1;background:#f1f5f9;border:1px solid #e5e7eb;border-radius:12px;padding:12px;font-weight:700;font-size:14px;">Descartar</button><button type="submit" style="flex:1;background:linear-gradient(180deg,#3a6bff,#2b5cff);color:white;border:0;border-radius:14px;padding:12px;font-weight:700;font-size:15px;box-shadow:0 8px 20px rgba(43,92,255,.2);">Confirmar e incorporar</button></div></form>';
 content().innerHTML=html;document.getElementById('doc-options').onclick=renderIAOptions;document.getElementById('doc-discard').onclick=renderIAOptions;document.getElementById('doc-form').onsubmit=save;
 if(draft.mode==='completar'){
  const updateCount=()=>{draft.checked=core.CONTRACT_FIELDS.filter(k=>document.getElementById('use-'+k)?.checked);document.getElementById('doc-selection-count').textContent=tenant?draft.checked.length+' campo(s) seleccionados para completar':'Selecciona la inquilina a completar';};
  content().querySelectorAll('[id^="use-"]').forEach(input=>input.onchange=updateCount);
  document.getElementById('doc-fill-empty').onclick=()=>{captureValues();draft.checked=core.completionSelection(tenant,draft.values);renderReview();};updateCount();
 }
 if(draft.mode==='renovar'&&tenant){const amount=document.getElementById('doc-fianzaImporte');if(amount)amount.oninput=()=>{const held=tenant.fianza?.estado==='retenida'?Number(tenant.fianza.importe||0):0;const agreed=Number(amount.value||0);document.getElementById('renewal-deposit').textContent='Fianza retenida: '+held.toFixed(2)+' €. Fianza del nuevo contrato: '+agreed.toFixed(2)+' €. Diferencia por revisar: '+(agreed-held).toFixed(2)+' €. No se registra ningún cobro ni devolución.';};}
 const target=document.getElementById('doc-target');if(target)target.onchange=()=>{captureValues();draft.selected=target.value;if(['completar','renovar'].includes(draft.mode))renderReview();};
 const kind=document.getElementById('doc-kind');if(kind)kind.onchange=()=>{captureValues();draft.mode=kind.value;renderReview();};
}
function captureValues(){if(!draft)return;for(const key of Object.keys(labels)){const input=document.getElementById('doc-'+key);if(input)draft.values[key]=input.value;}}
function transaction(changes){const before=Object.fromEntries(Object.keys(changes).map(k=>[k,localStorage.getItem(k)]));const serialized=Object.fromEntries(Object.entries(changes).map(([k,v])=>[k,JSON.stringify(v)]));try{for(const [k,v] of Object.entries(serialized))localStorage.setItem(k,v);}catch(e){for(const [k,v] of Object.entries(before)){try{if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}catch{}}throw Error('No se pudo guardar. No cierres la propuesta: exporta una copia o libera espacio del navegador y vuelve a intentarlo.');}}
function save(event){event.preventDefault();if(!draft)return;
 try{if(localStorage.getItem('donRamonV5')!==draft.stamp)throw Error('Los datos han cambiado desde la lectura. Vuelve a leer el documento para revisar sobre la ficha actual.');captureValues();const v={...draft.values,inquilinaId:document.getElementById('doc-target')?.value||null};const data=state(),meta={hash:draft.hash,name:draft.file.name,today:today()};let changes;
 if(['nueva','completar','renovar'].includes(draft.mode)){const selected=core.CONTRACT_FIELDS.filter(k=>document.getElementById('use-'+k)?.checked);changes={donRamonV5:draft.mode==='renovar'?core.renewal(data,v,meta,v.inquilinaId):core.contract(data,v,meta,draft.mode==='nueva'?null:draft.selected,selected)};}
 else if(draft.mode==='gasto'){if(window.rentV12Calc)window.rentV12Calc(today().slice(0,4));const result=core.expense(data,read('donRamonGastosReal',window.DonRamonSeeds?.gastosByMonth||{}),read('donRamonGastosV12',{}),v,meta);changes={donRamonGastosReal:result.rows,donRamonGastosV12:result.totals,donRamonV5:result.data};}
 else changes={donRamonV5:core.income(data,v,meta)};
 transaction(changes);draft=null;alert('Datos revisados e incorporados. Se actualizarán las fichas y los cálculos correspondientes. El archivo original no se ha archivado; consérvalo.');location.reload();
 }catch(e){document.getElementById('doc-error').textContent=e.message;}
}
function bindEntries(){document.querySelectorAll('button').forEach(button=>{const txt=button.textContent||'';if(txt.includes('Alta gasto con IA (recibo)')&&!button.dataset.docBound){button.dataset.docBound='1';button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();window.openIADoc();window.iaStart('gasto');},true);const badge=button.querySelector('span:last-child');if(badge?.textContent==='Próximamente')badge.textContent='Revisar';}});}
const observer=new MutationObserver(()=>bindEntries());observer.observe(document.getElementById('root'),{childList:true,subtree:true});bindEntries();
// Keep the established dashboard entry and its appearance.
function injectCard(){const divs=[...document.querySelectorAll('#root div')];for(const div of divs){if(!(div.textContent||'').includes('Próximas entradas')||!String(div.className).includes('rounded'))continue;const grid=div.parentElement;if(!String(grid?.className).includes('grid')||grid.querySelector('[data-document-assistant]'))continue;const card=document.createElement('button');card.dataset.documentAssistant='1';card.className='bg-white rounded-[20px] shadow-[0_4px_12px_rgba(0,0,0,.04)] p-4 flex flex-col gap-1 cursor-pointer';card.style.textAlign='left';card.innerHTML='<div style="display:flex;justify-content:space-between;width:100%;"><span style="font-size:12px;color:#6b7280;font-weight:600;">IA documental</span><span>🤖</span></div><div style="font-weight:800;font-size:18px;color:#0f172a;margin-top:4px;">Asistente IA</div><div style="font-size:12px;color:#6b7280;">Crear o completar desde documentos</div><div style="margin-top:8px;font-size:12px;font-weight:800;color:#7c3aed;">Abrir opciones</div>';card.onclick=window.openIADoc;grid.appendChild(card);}}
setInterval(injectCard,1000);setTimeout(injectCard,800);
})();
