(function(root){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
function eligible(file){const result=clone(file),old=result.entries.filter(e=>e.month<'2025-06');result.entries=result.entries.filter(e=>e.month>='2025-06');result.excludedSourceIds=[...new Set([...(result.excludedSourceIds||[]),...old.map(e=>e.sourceId)])];return result;}
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const cents=n=>Math.round(Number(n)*100);
function validDate(s){return /^\d{4}-(0[1-9]|1[0-2])-\d{2}$/.test(s)&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}
function validate(file){if(file?.format!=='don-ramon-expenses'||file.version!==1||!Array.isArray(file.entries)||file.entries.length>10000)throw Error('Archivo de gastos incompatible.');const ids=new Set();for(const e of file.entries){if(typeof e.sourceId!=='string'||!e.sourceId||ids.has(e.sourceId)||!validDate(e.date)||e.month!==e.date.slice(0,7)||typeof e.concept!=='string'||!e.concept.trim()||typeof e.category!=='string'||!e.category||!Number.isFinite(e.amount)||e.amount<=0||!Array.isArray(e.receipts))throw Error('Gasto incompleto, repetido o con fecha inválida.');ids.add(e.sourceId);}}
function parse(file){if(file?.format==='don-ramon-expenses'){validate(file);return eligible(file);}if(file?.exportType!=='alquileres-firestore-data')throw Error('Selecciona el JSON de gastos o la exportación de Firebase.');const rows=file.household?.collections?.expenses?.documents;if(!Array.isArray(rows))throw Error('La exportación no contiene gastos.');const result={format:'don-ramon-expenses',version:1,source:'Firebase',generatedAt:file.generatedAt,entries:rows.map(x=>{const e=x.data;return {sourceId:x.id,date:e.paidAt,month:e.paidAt?.slice(0,7),amount:Number(e.amount),concept:e.concept,category:e.category||'Otros',notes:e.notes||'',originalYear:e.year,originalMonth:e.expense_month??e.month??'',receipts:clone(e.receiptFiles?.length?e.receiptFiles:e.receiptFileName?[{fileName:e.receiptFileName,storagePath:e.receiptStoragePath||e.receiptLocationPath,contentType:e.receiptContentType,size:e.receiptSize}]:[])};})};validate(result);return eligible(result);}
function totals(file){const sums={};for(const e of file.entries){const y=e.date.slice(0,4);sums[y]??={count:0,cents:0};sums[y].count++;sums[y].cents+=cents(e.amount);}return sums;}
function plan(data,file){validate(file);const rows=Object.entries(data).flatMap(([month,list])=>{if(!Array.isArray(list))throw Error('Los gastos actuales tienen un formato inválido.');return list.map(row=>({month,row}));});return eligible(file).entries.map(e=>{const sameSource=rows.filter(x=>x.row.sourceId===e.sourceId||x.row.id==='firebase-expense:'+e.sourceId),matches=sameSource.length?sameSource:rows.filter(x=>{const r=x.row;return (r.fecha===e.date&&cents(r.importe)===cents(e.amount))||(x.month===e.month&&norm(r.concepto)===norm(e.concept))||(r.fecha===e.date&&norm(r.categoria)===norm(e.category));});const within=file.entries.some(other=>other.sourceId!==e.sourceId&&(other.date===e.date&&cents(other.amount)===cents(e.amount)&&norm(other.concept)===norm(e.concept)));return {e,matches,type:matches.length||within?'duplicate':'new',message:sameSource.length?'Este gasto ya fue importado.':matches.length?'Posible duplicado: coincide la fecha e importe, o el concepto y mes, o la fecha y categoría.':within?'Posible duplicado dentro del archivo. Revísalo antes de añadir.':'Nuevo gasto'};});}
function apply(data,file,choices={}){const next=clone(data),items=plan(data,file);let imported=0;const targets=new Set();for(const {e,matches,type} of items){const c=choices[e.sourceId]||{action:type==='new'?'import':'skip'};if(c.action==='skip')continue;if(!['import','update','add'].includes(c.action)||type==='duplicate'&&c.action==='import')throw Error('Revisa la acción del posible duplicado.');const existing=c.action==='update'?matches.find(x=>x.row.id===c.targetId):null;if(c.action==='update'&&!existing)throw Error('Selecciona el gasto concreto que deseas actualizar.');if(existing){if(targets.has(existing.row.id))throw Error('Dos gastos intentan actualizar el mismo registro.');targets.add(existing.row.id);next[existing.month]=next[existing.month].filter(r=>r.id!==existing.row.id);}
 const original=existing?.row||{},id=existing?original.id:'g_import_'+e.sourceId+'_'+Date.now()+'_'+imported;
 const notes=[e.notes,e.receipts.length?'Recibos originales (referencias; PDF pendiente de adjuntar): '+e.receipts.map(r=>r.fileName).join('; '):''].filter(Boolean).join('\n');
 const row={...original,id,fecha:e.date,concepto:e.concept,importe:e.amount,categoria:root.DonRamonLogicRepair?root.DonRamonLogicRepair.category({concepto:e.concept,categoria:e.category}):e.category,habitacion:original.habitacion||'General',notas:notes,sourceId:e.sourceId,sourceSystem:'Firebase',sourcePeriod:{year:e.originalYear,month:e.originalMonth},receiptReferences:clone(e.receipts),expenseImportHistory:[...(original.expenseImportHistory||[]),{action:c.action,importedAt:new Date().toISOString(),previous:existing?clone(existing.row):null}]};next[e.month]??=[];next[e.month].push(row);imported++;}return {data:next,imported};}
const api={parse,validate,plan,apply,totals};root.DonRamonExpenseImport=api;if(typeof module==='object')module.exports=api;
})(typeof window==='object'?window:globalThis);
