(function(root){
'use strict';
const cats=['Comunidad','Agua','Luz','Gas','Seguro','Impuestos','Internet','Otros'];
const amount=n=>Math.round(Number(n||0)*100)/100;
function expenses(ledger,month,category){return (ledger[month]||[]).filter(r=>(cats.includes(r.categoria)?r.categoria:'Otros')===category).slice().sort((a,b)=>a.fecha.localeCompare(b.fecha)||String(a.id).localeCompare(String(b.id)));}
function income(data,month){const groups=new Map(),people=data.inquilinas||[];function add(tenantId,room,value,compensation){const tenant=people.find(t=>t.id===tenantId)||root.DonRamonContracts?.occupantAt(people,Number(room),month),key=(tenant?.id||tenantId||'')+'|'+room;let row=groups.get(key);if(!row){row={room:Number(room),name:tenant?.nombre||'Inquilina sin identificar',cash:0,compensation:0};groups.set(key,row);}row[compensation?'compensation':'cash']=amount(row[compensation?'compensation':'cash']+value);}
 for(const row of data.cobrosByMonth?.[month]||[])add(row.inquilinaId,row.habitacion,row.status==='cobrado'?Number(row.amount||0):row.status==='parcial'?Number(row.importeParcial||0):0,false);
 for(const r of data.fianzasV2?.records||[])for(const m of r.movimientos||[])if(root.DonRamonDepositCore.imputationMonth(m)===month&&!m.contabilizadoEnCobro&&Number(m.aplicado||0)>0)add(r.inquilinaId,m.habitacion||r.habitacion,Number(m.aplicado),true);
 return [...groups.values()].map(r=>({...r,total:amount(r.cash+r.compensation)})).sort((a,b)=>a.room-b.room||a.name.localeCompare(b.name));
}
const api={expenses,income,cats};root.DonRamonProfitDetail=api;if(typeof module==='object')module.exports=api;if(!root.document)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),euro=n=>Number(n||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'}),months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
let inspectionYear=null;
const read=k=>JSON.parse(localStorage.getItem(k)||'{}'),year=()=>inspectionYear||String(root.DonRamonSelectedMonth||new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date())).slice(0,4),date=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('/'):'Sin fecha',titleMonth=m=>months[Number(m.slice(5,7))-1]+' '+m.slice(0,4);
function render(html){const el=document.getElementById('rent-v12-content');el.innerHTML='<div class="dr-profit">'+html+'</div>';el.querySelectorAll('[data-dr-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.drAction;if(a==='income-month')showIncome(b.dataset.month);if(a==='expense-month')showExpenses(b.dataset.month,b.dataset.category);if(a==='expense')showReceipt(b.dataset.month,b.dataset.category,b.dataset.id);if(a==='income-year')root.rentV12RenderIngresos();if(a==='categories')root.rentV12RenderGastosCategorias();if(a==='category')root.rentV12RenderCategoria(b.dataset.category);if(a==='summary')root.rentV12RenderResumen();if(a==='edit')edit(b.dataset.month,b.dataset.id);if(a==='receipt')openReceipt(b.dataset.month,b.dataset.id);});}
const back=(action,attrs='')=>'<button type="button" class="dr-back" data-dr-action="'+action+'" '+attrs+'>Volver</button>';
function attrs(m,c,id){return 'data-month="'+esc(m)+'" data-category="'+esc(c)+'"'+(id?' data-id="'+esc(id)+'"':'');}
function find(m,id){return (read('donRamonGastosReal')[m]||[]).find(r=>String(r.id)===id);}
function showIncome(month){const data=read('donRamonV5'),rows=income(data,month),total=root.DonRamonDepositCore.monthlyIncome(data,month);render(back('income-year')+'<h3>Ingresos · '+titleMonth(month)+'</h3>'+rows.map(r=>'<article class="dr-receipt"><div class="dr-row"><div><strong>Habitación '+r.room+'</strong><p>'+esc(r.name)+'</p></div><strong class="dr-money dr-green">'+euro(r.total)+'</strong></div>'+(r.compensation?'<p>Alquiler cobrado: '+euro(r.cash)+' · Fianza aplicada: '+euro(r.compensation)+'</p>':'')+'</article>').join('')+(!rows.length?'<p>No hay cobros registrados en este mes.</p>':'')+'<div class="dr-total dr-green">Total del mes <strong>'+euro(total)+'</strong></div>');}
function showExpenses(month,category){const rows=expenses(read('donRamonGastosReal'),month,category),total=rows.reduce((s,r)=>s+Math.round(r.importe*100),0)/100;render(back('category','data-category="'+esc(category)+'"')+'<h3>'+esc(category)+' · '+titleMonth(month)+'</h3>'+rows.map(r=>'<button type="button" class="dr-receipt dr-receipt-button" data-dr-action="expense" '+attrs(month,category,String(r.id))+'><span class="dr-row"><span><strong>'+esc(r.concepto)+'</strong><span class="dr-meta">'+date(r.fecha)+'</span></span><strong class="dr-money">'+euro(r.importe)+'</strong></span><span class="dr-meta dr-blue">Ver detalle</span></button>').join('')+(!rows.length?'<p>No hay recibos individuales registrados en este mes.</p>':'')+'<div class="dr-total">Total del mes <strong>'+euro(total)+'</strong></div>');}
function showReceipt(month,category,id){const r=find(month,id);if(!r){showExpenses(month,category);return;}const hasReceipt=typeof r.justificante==='string'&&r.justificante.trim();render(back('expense-month',attrs(month,category))+'<h3>Detalle del recibo</h3><article class="dr-receipt"><div class="dr-row"><strong>'+esc(r.concepto)+'</strong><strong class="dr-money">'+euro(r.importe)+'</strong></div><p>'+date(r.fecha)+' · '+esc(r.categoria)+' · '+esc(r.habitacion||'General')+'</p>'+(r.notas?'<p class="dr-notes">'+esc(r.notas)+'</p>':'')+((r.receiptReferences||[]).length?'<p>Recibos originales: '+r.receiptReferences.map(x=>esc(x.fileName)).join('; ')+'</p>':'')+'<div class="dr-actions">'+(hasReceipt?'<button type="button" data-dr-action="receipt" '+attrs(month,category,id)+'>Ver justificante</button>':'<p>Justificante pendiente de adjuntar.</p>')+'<button type="button" data-dr-action="edit" '+attrs(month,category,id)+'>Editar en Gastos</button></div><p id="dr-receipt-message" role="status"></p></article>');}
function edit(month,id){const r=find(month,id);if(!r)return;root.DonRamonEditExpense?.(r,month);}
function openReceipt(month,id){const r=find(month,id);try{const u=new URL(r.justificante,location.href);if(!['https:','http:','blob:'].includes(u.protocol)&&!/^data:(application\/pdf|image\/)/.test(r.justificante))throw Error('El enlace del justificante no es válido.');root.open(u.href,'_blank','noopener,noreferrer');}catch(e){document.getElementById('dr-receipt-message').textContent=e.message;}}
function init(){Object.defineProperty(root,'DonRamonProfitInspectionYear',{get:()=>inspectionYear,configurable:true});const originalOpen=root.openRentabilidadV12;root.openRentabilidadV12=()=>{inspectionYear=null;originalOpen();};root.openAnalysisDetails=(kind,month)=>{inspectionYear=month.slice(0,4);document.getElementById('rentabilidad-v12-overlay').style.display='flex';if(kind==='income')showIncome(month);else{render(back('summary')+'<h3>Gastos · '+titleMonth(month)+'</h3>'+cats.map(cat=>{const rows=expenses(read('donRamonGastosReal'),month,cat),total=rows.reduce((s,r)=>s+Math.round(r.importe*100),0)/100;return '<button type="button" class="dr-month" data-dr-action="expense-month" '+attrs(month,cat)+'><span class="dr-row"><span>'+esc(cat)+'</span><strong>'+euro(total)+'</strong></span></button>';}).join(''));}};const style=document.createElement('style');style.textContent='.dr-profit{font-size:16px;min-width:0}.dr-profit h3{font-size:18px;font-weight:800;margin:16px 0}.dr-profit button{font:inherit;cursor:pointer;background:white;color:#2b5cff;border:1px solid #e5e7eb;border-radius:14px;padding:12px 16px;min-height:44px}.dr-profit button:focus-visible{outline:2px solid #2b5cff;outline-offset:2px}.dr-profit .dr-back{font-size:14px}.dr-row,.dr-total{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.dr-row>span,.dr-row>div{min-width:0}.dr-money{white-space:nowrap;color:#1e40af}.dr-receipt{background:white;border:1px solid #e5e7eb;border-radius:16px;padding:16px;margin:12px 0;overflow-wrap:anywhere}.dr-profit .dr-receipt-button{display:block;text-align:left;width:100%;color:#0f172a}.dr-profit p,.dr-meta{font-size:14px;color:#64748b;line-height:1.5;margin:8px 0}.dr-meta{display:block}.dr-blue{color:#2b5cff}.dr-green{color:#15803d}.dr-total{background:#eff6ff;border:1px solid #dbeafe;border-radius:14px;padding:16px;margin-top:16px}.dr-total.dr-green{background:#f0fdf4;border-color:#bbf7d0}.dr-notes{white-space:pre-wrap}.dr-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.dr-month{display:block;width:100%;text-align:left;margin:8px 0}.dr-profit .dr-month .dr-row{align-items:center}.dr-month small{display:block;font-size:14px;color:#64748b;margin-top:4px}';document.head.appendChild(style);
 root.rentV12RenderIngresos=()=>{const y=year(),calc=root.rentV12Calc(y);render(back('summary')+'<h3>Ingresos '+y+' · '+euro(calc.totalIngresos)+'</h3>'+months.map((name,i)=>{const m=y+'-'+String(i+1).padStart(2,'0');return '<button type="button" class="dr-month" data-dr-action="income-month" data-month="'+m+'"><span class="dr-row"><span>'+name+'<small>Ver habitaciones e inquilinas</small></span><strong class="dr-green">'+euro(calc.ingresosPorMes[i+1])+'</strong></span></button>';}).join(''));};
 root.rentV12RenderCategoria=category=>{const y=year(),calc=root.rentV12Calc(y);render(back('categories')+'<h3>'+esc(category)+' · '+euro(calc.gastosPorCat[category])+'</h3>'+months.map((name,i)=>{const m=y+'-'+String(i+1).padStart(2,'0'),rows=expenses(read('donRamonGastosReal'),m,category),total=calc.gastosPorMesCat[category]?.[i+1]||0;return '<button type="button" class="dr-month" data-dr-action="expense-month" '+attrs(m,category)+'><span class="dr-row"><span>'+name+'<small>'+rows.length+' '+(rows.length===1?'recibo':'recibos')+' · Ver detalle</small></span><strong>'+euro(total)+'</strong></span></button>';}).join(''));};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(typeof window==='object'?window:globalThis);
