(function(root){
'use strict';
function install(React){if(api.PaymentPanel)return api;const h=React.createElement,C=root.DonRamonRoomCore,D=root.DonRamonDepositCore,euro=n=>Number(n||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'}),input='w-full bg-white border rounded-[12px] px-4 py-3 text-[16px]',button='w-full rounded-[14px] py-3 text-[15px] font-bold bg-[#2b5cff] text-white';
 const field=(label,type,value,onChange,extra={})=>h('label',{className:'flex flex-col gap-2'},h('span',{className:'text-sm font-bold'},label),h('input',{type,value,className:input,onChange:e=>onChange(e.target.value),...extra}));
 function PaymentPanel({data,room,initialMonth,onChange,onClose}){
  const [month,setMonth]=React.useState(initialMonth),[values,setValues]=React.useState({index:'',amount:'',date:'',method:'Sin indicar',notes:''}),[error,setError]=React.useState('');
  const rows=C.paymentRows(data,room,month),set=(key,v)=>setValues(old=>({...old,[key]:v}));
  const select=(index)=>{const row=rows.find(x=>String(x.index)===String(index))?.row;setValues({index,amount:row&&C.cash(row)>0?C.cash(row):'',date:row?.fechaAbono||'',method:row?.metodo||'Sin indicar',notes:row?.notas||''});setError('');};
  React.useEffect(()=>{select(rows.length===1?String(rows[0].index):'');},[month,room,data.cobrosByMonth]);
  let context;try{context=C.receiptOwner(data,room,month,values.index);}catch{}
  const card=D.receipt(data,room,month);
  return h('form',{className:'flex flex-col gap-4',onSubmit:e=>{e.preventDefault();try{onChange(C.savePayment(data,room,{...values,month}));onClose();}catch(err){setError(err.message);}}},field('Mes al que corresponde el alquiler','month',month,setMonth,{min:'2025-06',required:true}),
   h('label',{className:'flex flex-col gap-2'},h('span',{className:'text-sm font-bold'},'Cobro que quieres registrar o editar'),h('select',{className:input,value:values.index,onChange:e=>select(e.target.value)},h('option',{value:''},'Nuevo cobro'),rows.map(({row,index})=>h('option',{key:index,value:String(index)},(C.identity(data,row,room,month)?.nombre||'Sin inquilina identificada')+' · '+(row.status==='pendiente'?'Pendiente':euro(C.cash(row)))+' · '+(row.fechaAbono||'Sin fecha'))))),
   h('div',{className:'bg-[#f8fafc] rounded-[14px] p-4 text-sm'},h('strong',null,context?.tenant?.nombre||'Contrato por vincular'),h('p',null,'Esperado según contrato/acuerdo: '+(context?.expected!==null&&context?.expected!==undefined?euro(context.expected):'Sin dato')),h('p',null,'Ingresos registrados para la estancia del mes: '+euro(card.received))),
   field('Importe realmente cobrado €','number',values.amount,v=>set('amount',v),{min:'0.01',step:'0.01',required:true}),field('Fecha real del abono','date',values.date,v=>set('date',v),{required:true}),
   h('label',{className:'flex flex-col gap-2'},h('span',{className:'text-sm font-bold'},'Método de cobro'),h('select',{className:input,value:values.method,onChange:e=>set('method',e.target.value)},['Sin indicar','Transferencia','Bizum','Efectivo','Domiciliación','Otro',...(/fianza|compensaci/i.test(values.method)?[values.method]:[])].map(m=>h('option',{key:m,value:m},m)))),
   h('label',{className:'flex flex-col gap-2'},h('span',{className:'text-sm font-bold'},'Notas'),h('textarea',{className:input,value:values.notes,onChange:e=>set('notes',e.target.value)})),error&&h('p',{role:'alert',className:'text-sm text-red-700'},error),h('button',{type:'submit',className:button},'Guardar cobro'),values.index!==''&&rows.some(x=>String(x.index)===values.index&&C.cash(x.row)>0)&&h('button',{type:'button',className:input+' text-red-700 font-bold',onClick:()=>{if(!root.confirm('¿Anular este cobro? Su importe anterior se conservará en el historial de cambios.'))return;try{onChange(C.cancelPayment(data,room,month,values.index));onClose();}catch(err){setError(err.message);}}},'Anular este cobro'),h('button',{type:'button',onClick:onClose,className:input+' font-bold text-[#2b5cff]'},'Volver'));
 }
 function IncomePanel({data,expenses,room,mode='analysis',onClose}){
  const result=C.analysis(data,expenses,room),metric=(label,value)=>h('div',{className:'bg-[#f8fafc] rounded-[14px] p-3'},h('div',{className:'text-sm text-slate-500'},label),h('strong',{className:'block mt-1 text-base'},value));
  const record=(r,i)=>h('article',{key:r.id||r.month+'_'+i,className:'border rounded-[14px] p-4 text-sm'},h('strong',null,r.month+' · '+r.name),h('p',null,r.kind+(r.future?' · Mes o abono futuro':'')),h('p',null,r.status==='pendiente'?'Previsto: '+euro(r.amount):euro(r.actual)),h('p',{className:'text-slate-500'},(r.fechaAbono||'Fecha sin indicar')+' · '+(r.metodo||'Medio sin indicar')),r.notas&&h('p',null,r.notas));
  return h('div',{className:'grid gap-3'},mode==='history'?h(React.Fragment,null,h('p',{className:'text-sm text-slate-500'},result.collectionMonths+' meses con ingresos registrados. Los pendientes y meses futuros aparecen identificados.'),[...new Set(result.records.map(r=>r.month.slice(0,4)))].sort().reverse().map(year=>h('details',{key:year,className:'border rounded-[14px] p-4'},h('summary',{className:'font-bold cursor-pointer'},year),h('div',{className:'grid gap-3 mt-3'},result.records.filter(r=>r.month.startsWith(year)).map(record)))),!result.records.length&&h('p',null,'Sin cobros registrados.')):
   h(React.Fragment,null,h('div',{className:'grid grid-cols-2 gap-3'},metric('Ingresos obtenidos',euro(result.total)),metric('Gastos asignados a la habitación',euro(result.expenses))),h('p',{className:'text-sm text-slate-500'},'Los ingresos proceden de sus cobros y fianzas aplicadas, contados una sola vez. Los gastos generales del inmueble y el IRPF se consultan en Rent; no se reparten automáticamente entre habitaciones.'),result.years.map(year=>h('details',{key:year.year,className:'border rounded-[14px] p-4',open:true},h('summary',{className:'font-bold cursor-pointer'},year.year+' · Obtenido '+euro(year.actual)),h('div',{className:'grid grid-cols-2 gap-3 mt-3'},metric('Esperado firmado del año'+(year.missing?' · datos parciales':''),euro(year.expected)),metric('Saldo tras gastos asignados',euro(year.actual-year.expenses))),year.months.map(m=>h('details',{key:m.month,className:'border-t mt-3 pt-3 text-sm'},h('summary',{className:'cursor-pointer font-bold'},m.month+' · '+(m.future?'Futuro':euro(m.actual))),h('p',null,'Esperado '+(m.expected===null?'Sin dato contractual':euro(m.expected))+' · Obtenido '+euro(m.actual)),!m.future&&h('p',null,'Gastos asignados '+euro(m.expenses)+' · Saldo '+euro(m.net)),h('div',{className:'grid gap-2 mt-2'},result.records.filter(r=>r.month===m.month).map(record)),(expenses[m.month]||[]).filter(e=>Number(String(e.habitacion||'').match(/\d+/)?.[0])===Number(room)).map(e=>h('p',{key:e.id},'Gasto · '+(e.fecha||'Fecha sin indicar')+' · '+e.concepto+' · '+euro(e.importe)))))))),h('button',{type:'button',onClick:onClose,className:input+' font-bold text-[#2b5cff]'},'Volver'));
 }
 api.PaymentPanel=PaymentPanel;api.IncomePanel=IncomePanel;return api;
}
const api={install};root.DonRamonRoomUI=api;
})(typeof window==='object'?window:globalThis);
